### ISSUE TITLE
vue add cordova fail on MacOS

### ISSUE THREAD

**Issue by Akirami** [dekimasoon/vue-cli-plugin-cordova#16] opened 2018-06-14 16:44 UTC
Hello, great work but still error when i make a fresh install with node version v10.4.1,  Cordova v8.0.0 and vue/cli@3.0.0-rc.2

```
vue add cordova

📦  Installing vue-cli-plugin-cordova...

yarn add v1.7.0
info No lockfile found.
[1/4] 🔍  Resolving packages...
⠁ (node:74065) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 118 new dependencies.
info Direct dependencies
└─ vue-cli-plugin-cordova@1.0.0-beta.6
info All dependencies
├─ @vue/cli-shared-utils@3.0.0-rc.2
├─ address@1.0.3
├─ ajv@5.5.2
├─ ansi-styles@3.2.1
├─ asn1@0.2.3
├─ async@1.5.2
├─ asynckit@0.4.0
├─ aws-sign2@0.7.0
├─ aws4@1.7.0
├─ balanced-match@1.0.0
├─ bcrypt-pbkdf@1.0.1
├─ brace-expansion@1.1.11
├─ caseless@0.12.0
├─ chalk@2.4.1
├─ cli-cursor@2.1.0
├─ cli-spinners@1.3.1
├─ co@4.6.0
├─ color-convert@1.9.2
├─ color-name@1.1.1
├─ combined-stream@1.0.6
├─ concat-map@0.0.1
├─ cordova-plugin-device@2.0.2
├─ core-util-is@1.0.2
├─ cross-spawn@6.0.5
├─ dashdash@1.14.1
├─ debug@2.6.9
├─ define-properties@1.1.2
├─ delayed-stream@1.0.0
├─ easy-stack@1.0.0
├─ ecc-jsbn@0.1.1
├─ ejs@2.6.1
├─ es-abstract@1.12.0
├─ es-to-primitive@1.1.1
├─ escape-string-regexp@1.0.5
├─ event-pubsub@4.3.0
├─ execa@0.10.0
├─ extend@3.0.1
├─ extsprintf@1.3.0
├─ fast-deep-equal@1.1.0
├─ fast-json-stable-stringify@2.0.0
├─ foreach@2.0.5
├─ forever-agent@0.6.1
├─ form-data@2.3.2
├─ fs.realpath@1.0.0
├─ get-stream@3.0.0
├─ getpass@0.1.7
├─ glob@7.1.2
├─ har-schema@2.0.0
├─ har-validator@5.0.3
├─ has-flag@3.0.0
├─ html-webpack-include-assets-plugin@1.0.4
├─ http-signature@1.2.0
├─ inflight@1.0.6
├─ inherits@2.0.3
├─ is-callable@1.1.3
├─ is-date-object@1.0.1
├─ is-regex@1.0.4
├─ is-stream@1.1.0
├─ is-symbol@1.0.1
├─ is-typedarray@1.0.0
├─ is-wsl@1.1.0
├─ isemail@3.1.2
├─ isexe@2.0.0
├─ isstream@0.1.2
├─ joi@12.0.0
├─ js-message@1.0.5
├─ js-queue@2.0.0
├─ json-schema-traverse@0.3.1
├─ json-schema@0.2.3
├─ json-stringify-safe@5.0.1
├─ jsprim@1.4.1
├─ lodash@4.17.10
├─ log-symbols@2.2.0
├─ mime-db@1.33.0
├─ mime-types@2.1.18
├─ mimic-fn@1.2.0
├─ minimist@0.0.8
├─ mkdirp@0.5.1
├─ ms@2.0.0
├─ nice-try@1.0.4
├─ node-ipc@9.1.1
├─ npm-run-path@2.0.2
├─ oauth-sign@0.8.2
├─ object-keys@1.0.11
├─ onetime@2.0.1
├─ opn@5.3.0
├─ ora@1.4.0
├─ p-finally@1.0.0
├─ path-is-absolute@1.0.1
├─ path-key@2.0.1
├─ performance-now@2.1.0
├─ portfinder@1.0.13
├─ psl@1.1.28
├─ qs@6.5.2
├─ request-promise-core@1.1.1
├─ request-promise-native@1.0.5
├─ request@2.87.0
├─ restore-cursor@2.0.0
├─ safe-buffer@5.1.2
├─ safer-buffer@2.1.2
├─ semver@5.5.0
├─ shebang-command@1.2.0
├─ shebang-regex@1.0.0
├─ signal-exit@3.0.2
├─ slash@1.0.0
├─ sshpk@1.14.2
├─ stealthy-require@1.1.1
├─ string.prototype.padstart@3.0.0
├─ strip-eof@1.0.0
├─ supports-color@5.4.0
├─ topo@2.0.2
├─ tough-cookie@2.4.2
├─ tunnel-agent@0.6.0
├─ tweetnacl@0.14.5
├─ uuid@3.2.1
├─ verror@1.10.0
├─ vue-cli-plugin-cordova@1.0.0-beta.6
└─ which@1.3.1
✨  Done in 4.48s.

✔  Successfully installed plugin: vue-cli-plugin-cordova


🚀  Invoking generator for vue-cli-plugin-cordova...
📦  Installing additional dependencies...
yarn install v1.7.0
[1/4] 🔍  Resolving packages...
⠁ (node:74066) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
✨  Done in 36.41s.
⠋  Running completion hooks... ERROR  Error: ENOENT: no such file or directory, symlink '../platforms' -> './public/cordova'
Error: ENOENT: no such file or directory, symlink '../platforms' -> './public/cordova'
    at Object.fs.symlinkSync (fs.js:1002:3)
    at api.onCreateComplete (/Users/akira/Documents/Native-App/SnD-Cordova2/node_modules/vue-cli-plugin-cordova/generator/index.js:101:8)
    at runGenerator (/usr/local/lib/node_modules/@vue/cli/lib/invoke.js:131:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by dekimasoon** [comment] 2018-06-15 04:57
Hi @Akirami, thank you for opening new issue!
I am sorry that I could not reply last night. It was 3am in my time zone.

I did try to reproduce your issue, but I couldn't.
The only possibility I noticed is that there is no `public` dir in your project.

I think that it is misplaced because your issue occurs on a fresh installation, but could you please confirm it just in case?

My env:
```
MacOS 10.12.6
node 10.4.1
yarn 1.7.0
@vue/cli 3.0.0-rc.2
vue-cli-plugin-cordova 1.0.0-beta.7
```

**Comment by Akirami** [comment] 2018-06-15 05:43
Hi @dekimasoon,

MacOS 10.13.5
Node 10.4.1
Yarn 1.7.0
vue-cli-plugin-cordova 1.0.0-beta.7
@vue/cli 3.0.0-rc.2 is the global  version i have but if i check the version in the directory where I installed vue-cli-plugin-cordova (npm list vue), it's vue@2.5.16 and the vue-cli-service fail. 

So, i created  a new project with "vue create myapp" instead of "vue init webpack myapp" and the vue version is the good one this time and after test, all work with livereload. I think webpack limit the vue version to 2.5.

>I am sorry that I could not reply last night. It was 3am in my time zone.

You dont have to be sorry, you do a very good work and i will save a lot of time thanks to you ;)

**Comment by dekimasoon** [comment] 2018-06-15 14:22
I am glad to hear that you solved the problem!
Close this one and see you next one lol

**Closed by dekimasoon** 2018-06-15 14:22 UTC
