### ISSUE TITLE
vue add cordova fails on windows 10

### ISSUE THREAD

**Issue by evinkuraga** [dekimasoon/vue-cli-plugin-cordova#15] opened 2018-06-13 16:31 UTC
On a fresh install When running the steps described: 
```
$ vue add cordova
$ npm run cordova-build
$ cordova prepare
$ npm run cordova-serve

# in another tab
$ cordova run android
```

I can  see the preview on localhost:8080, but I can't see it on android. What I see on my android mobile device (pixel2) is a blank white screen. 

Also note: 
On windows 10 env, the command vue add cordova generates the following error unless the CLI is ran as an administrator. : 
-  Running completion hooks... ERROR  Error: EPERM: operation not permitted, symlink '..\platforms' -> 'C:\Users\me\Code\test\public\cordova'
Error: EPERM: operation not permitted, symlink '..\platforms' -> 'C:\Users\me\Code\test\public\cordova'

OS : windows 10
npm : 6.1.0
node : 8.11.2
vue-cli: 3.0.0-beta.16

**Comment by evinkuraga** [comment] 2018-06-13 17:04
I ran the command again as by running the CLI as administrator, worked fine, but created duplicate imports in the main.js file, which needed to be removed manually to get it to work.

Aside from that, fantastic plugin. Well done! Huge time saver!

**Comment by dekimasoon** [comment] 2018-06-14 05:52
Hi @evinkuraga, thank you for trying this plugin!

I assume your first issue is somehow related to a redirect. In development, this plugin replaces your index.html to this [redirect.ejs](https://github.com/dekimasoon/vue-cli-plugin-cordova/blob/master/redirect.ejs) for redirecting to webpack-dev-server running on your pc. If this redirect failed, blank white screen appears.

I will try to reproduce your problem tonight. If possible, fix the plugin so that you can easily detect if the redirect failed or not.

> On windows 10 env, the command vue add cordova generates the following error unless the CLI is ran as an administrator. 

Yes, you are right. I have to fix this plugin so that it does not use symlink. Until then I will add notes to startguide.

Thank you for your reporting, and please wait until my work is completed.

**Comment by Akirami** [comment] 2018-06-14 16:03
Also fail on MacOS 
` Running completion hooks... ERROR  Error: ENOENT: no such file or directory, symlink '../platforms' -> './public/cordova'
Error: ENOENT: no such file or directory, symlink '../platforms' -> './public/cordova'
    at Object.fs.symlinkSync (fs.js:1002:3)
    at api.onCreateComplete (/.../node_modules/vue-cli-plugin-cordova/generator/index.js:101:8)
    at runGenerator (/usr/local/lib/node_modules/@vue/cli/lib/invoke.js:131:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
`

**Comment by dekimasoon** [comment] 2018-06-14 16:30
Hi @Akirami, sorry for your  inconvenience. Cloud you please open new issue?  
I also need more details to debug your problem. Providing the repo I can clone to reproduce the problem is the best.

**Comment by dekimasoon** [comment] 2018-06-14 18:38
@evinkuraga Cloud you try 1.0.0-beta.7? I just published!
Hope it will work. I am worried because I have not debugged enough.

**Comment by evinkuraga** [comment] 2018-06-14 19:08
In a fresh installation, I now get to the screen : 

> ... redirecting to dev server: 192.168.**.*:8081 
> This screen only shown in development mode. If your app hands up on this creen, please check the following. 
>  - The dev server is running properly with .....

Can't wait to get this working. This plugging with be a GOLD mine  to the vuejs community! Thanks for looking into this!

**Comment by dekimasoon** [comment] 2018-06-15 05:33
Thanks for trying the new version!
Last night, my Windows 10 and the old xperia (android 4.4) worked fine.

As you can see from the displayed message, it seems that there is a problem connecting to the dev server running on pc from your android device. 

Could you please check whether the IP address listed in the message (192.168. **. *: 8081) can be accessed from your Android with chrome?

If you can not access it, there may be problems with your lan environment. If you can, I need to get new android device from somewhere lol

**Comment by dekimasoon** [comment] 2018-06-19 07:03
In order to keep the issue list clean, I think I will close this issue once.
If you have problems, please reopen it at any time.

**Closed by dekimasoon** 2018-06-19 07:03 UTC

**Comment by evinkuraga** [comment] 2018-06-19 17:54
Woah sorry, I just saw you wrote back! I eventually managed to get it to work. I uninstalled and reinstalled everything, including android sdk and any all android directories as well as my IDE (intellij idea). Then I updated every package to the latest (vue cli, yours). Not sure where the issue was specifically, but probably a conflict with a version of something.

On another note, thanks for adding the comment in your read me file about running commands as administrator! I think you might want to be a bit more specific about it though. 
It's actually the CLI (or command prompt) that needs to be ran as an administrator (Done by right clicking the app > more > run as administrator.)
I'm not sure everyone will understand it unless you explicitly say it. 

Finally, thanks a million for this package! Fantastic work and hugely helpful!

**Comment by dekimasoon** [comment] 2018-06-21 05:13
@evinkuraga Thank you for your reply!
Your suggestion has been very helpful. Since I am not a native speaker of English, I wanted to update it as easily as I could, and it was wrong.
I'll update comments for Windows users more specific as you pointed out.
